---
name: github-ls
version: 0.0.0.0

license: MIT
license-file: LICENSE

dependencies:
  - base
  - bytestring
  - github
  - optparse-applicative
  - optparse-generic
  - relude
  - text
  - turtle
  - vector

library:
  source-dirs: ./src/

executables:
  github-ls:
    main: Main.hs
    source-dirs: ./src/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
