---
name: github-ls
version: 1.0.1

license: MIT
license-file: LICENSE

dependencies:
  - base
  - bytestring
  - github
  - optparse-applicative
  - optparse-generic
  - relude
  - text
  - turtle
  - vector
  - vector-algorithms

library:
  source-dirs: ./src/

executables:
  github-ls:
    main: Main.hs
    source-dirs: ./src/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  github-ls-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - genvalidity
      - genvalidity-sydtest
      - genvalidity-text
      - github-ls
      - QuickCheck
      - sydtest
      - sydtest-discover
      - validity
