name: build
on: push
#
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install nix
        uses: cachix/install-nix-action@master
      - uses: cachix/cachix-action@master
        with:
          name: opensource
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --accept-flake-config

  build-dev-shell:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install nix
        uses: cachix/install-nix-action@master
      - uses: cachix/cachix-action@master
        with:
          name: opensource
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#devShells.x86_64-linux.default --accept-flake-config
